shared: &shared
	stylist:
		name:               "Stylist"
		email_address:      "stylist@example.com"
		from_email_address: "no-reply@example.com"
	smtp:
		address:              "mail.example.com"
		port:                 587
		user_name:            "username@example.com"
		password:             "super-secret"
		authentication:       "login"
		enable_starttls_auto: true

production:
	<<: *shared

development:
	<<: *shared

test:
	<<: *shared